---
services:
  aura-proxy:
    container_name: aura-proxy
    image: ghcr.io/adm-metaex/aura-proxy/aura-proxy:develop-8aaf838
    restart: unless-stopped
    tty: true
    ports:
      - "${PROXY_PORT}:${PROXY_PORT}"
      - "${PROXY_METRICS_PORT}:${PROXY_METRICS_PORT}"
    env_file:
      - .env
    # entrypoint: "proxy"
    volumes:
      - ./PROXY_CERT_FILE:/app/PROXY_CERT_FILE:ro
    deploy:
      resources:
        limits:
          cpus: "0.75"
          memory: 7000M
    command:
      - -log=debug
    logging:
      options:
        max-size: "5g"
    networks:
      - aura-gw
    labels:
      - aura-proxy=healthy
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:$PROXY_PORT/service-status | egrep -q 'status\":\"operational\"' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
networks:
  aura-gw:
    driver: bridge
    name: aura-gw
